# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_breakfast.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_breakfast(object):
    def setupUi(self, choose_breakfast):
        choose_breakfast.setObjectName("choose_breakfast")
        choose_breakfast.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        choose_breakfast.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        choose_breakfast.setWindowIcon(icon)
        self.breakfast_menu_list = QtWidgets.QListWidget(choose_breakfast)
        self.breakfast_menu_list.setGeometry(QtCore.QRect(10, 10, 381, 581))
        self.breakfast_menu_list.setObjectName("breakfast_menu_list")
        self.breakfast_recipe_list = QtWidgets.QListWidget(choose_breakfast)
        self.breakfast_recipe_list.setGeometry(QtCore.QRect(410, 10, 381, 391))
        self.breakfast_recipe_list.setObjectName("breakfast_recipe_list")
        self.label = QtWidgets.QLabel(choose_breakfast)
        self.label.setGeometry(QtCore.QRect(390, 420, 401, 121))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cancel_button = QtWidgets.QPushButton(choose_breakfast)
        self.cancel_button.setGeometry(QtCore.QRect(580, 560, 91, 31))
        self.cancel_button.setObjectName("cancel_button")
        self.yes_button = QtWidgets.QPushButton(choose_breakfast)
        self.yes_button.setGeometry(QtCore.QRect(690, 560, 91, 31))
        self.yes_button.setObjectName("yes_button")

        self.retranslateUi(choose_breakfast)
        QtCore.QMetaObject.connectSlotsByName(choose_breakfast)

    def retranslateUi(self, choose_breakfast):
        _translate = QtCore.QCoreApplication.translate
        choose_breakfast.setWindowTitle(_translate("choose_breakfast", "选择早餐"))
        self.label.setText(_translate("choose_breakfast", "双击左侧列表项添加食物\n"
"双击右侧列表项移除食物\n"
"多份食物请多次双击添加"))
        self.cancel_button.setText(_translate("choose_breakfast", "取消"))
        self.yes_button.setText(_translate("choose_breakfast", "确定"))
