# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_gender.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_gender(object):
    def setupUi(self, choose_gender):
        choose_gender.setObjectName("choose_gender")
        choose_gender.resize(300, 70)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        choose_gender.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        choose_gender.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(choose_gender)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boy_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.boy_button.setObjectName("boy_button")
        self.horizontalLayout.addWidget(self.boy_button)
        self.girl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.girl_button.setObjectName("girl_button")
        self.horizontalLayout.addWidget(self.girl_button)

        self.retranslateUi(choose_gender)
        QtCore.QMetaObject.connectSlotsByName(choose_gender)

    def retranslateUi(self, choose_gender):
        _translate = QtCore.QCoreApplication.translate
        choose_gender.setWindowTitle(_translate("choose_gender", "选择性别"))
        self.boy_button.setText(_translate("choose_gender", "我是男生"))
        self.girl_button.setText(_translate("choose_gender", "我是女生"))
