# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_lunch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_lunch(object):
    def setupUi(self, choose_lunch):
        choose_lunch.setObjectName("choose_lunch")
        choose_lunch.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        choose_lunch.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        choose_lunch.setWindowIcon(icon)
        self.lunch_menu_list = QtWidgets.QListWidget(choose_lunch)
        self.lunch_menu_list.setGeometry(QtCore.QRect(10, 10, 381, 581))
        self.lunch_menu_list.setObjectName("lunch_menu_list")
        self.lunch_recipe_list = QtWidgets.QListWidget(choose_lunch)
        self.lunch_recipe_list.setGeometry(QtCore.QRect(410, 10, 381, 391))
        self.lunch_recipe_list.setObjectName("lunch_recipe_list")
        self.label = QtWidgets.QLabel(choose_lunch)
        self.label.setGeometry(QtCore.QRect(390, 420, 401, 121))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cancel_button = QtWidgets.QPushButton(choose_lunch)
        self.cancel_button.setGeometry(QtCore.QRect(580, 560, 91, 31))
        self.cancel_button.setObjectName("cancel_button")
        self.yes_button = QtWidgets.QPushButton(choose_lunch)
        self.yes_button.setGeometry(QtCore.QRect(690, 560, 91, 31))
        self.yes_button.setObjectName("yes_button")

        self.retranslateUi(choose_lunch)
        QtCore.QMetaObject.connectSlotsByName(choose_lunch)

    def retranslateUi(self, choose_lunch):
        _translate = QtCore.QCoreApplication.translate
        choose_lunch.setWindowTitle(_translate("choose_lunch", "选择午餐"))
        self.label.setText(_translate("choose_lunch", "双击左侧列表项添加食物\n"
"双击右侧列表项移除食物\n"
"多份食物请多次双击添加"))
        self.cancel_button.setText(_translate("choose_lunch", "取消"))
        self.yes_button.setText(_translate("choose_lunch", "确定"))
