# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_load_file(object):
    def setupUi(self, load_file):
        load_file.setObjectName("load_file")
        load_file.resize(400, 130)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        load_file.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(load_file)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 361, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.path_label.setFont(font)
        self.path_label.setObjectName("path_label")
        self.horizontalLayout.addWidget(self.path_label)
        self.path_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.horizontalLayout.addWidget(self.path_lineEdit)
        self.file_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.file_Button.setObjectName("file_Button")
        self.horizontalLayout.addWidget(self.file_Button)
        self.cancel_button = QtWidgets.QPushButton(load_file)
        self.cancel_button.setGeometry(QtCore.QRect(220, 100, 75, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.yes_button = QtWidgets.QPushButton(load_file)
        self.yes_button.setGeometry(QtCore.QRect(300, 100, 75, 23))
        self.yes_button.setObjectName("yes_button")
        self.boy_button = QtWidgets.QRadioButton(load_file)
        self.boy_button.setGeometry(QtCore.QRect(220, 60, 86, 31))
        self.boy_button.setChecked(True)
        self.boy_button.setObjectName("boy_button")
        self.girl_button = QtWidgets.QRadioButton(load_file)
        self.girl_button.setGeometry(QtCore.QRect(300, 60, 86, 31))
        self.girl_button.setObjectName("girl_button")

        self.retranslateUi(load_file)
        QtCore.QMetaObject.connectSlotsByName(load_file)

    def retranslateUi(self, load_file):
        _translate = QtCore.QCoreApplication.translate
        load_file.setWindowTitle(_translate("load_file", "导入文件"))
        self.path_label.setText(_translate("load_file", "文件路径"))
        self.file_Button.setText(_translate("load_file", "浏览..."))
        self.cancel_button.setText(_translate("load_file", "取消"))
        self.yes_button.setText(_translate("load_file", "确定"))
        self.boy_button.setText(_translate("load_file", "男生"))
        self.girl_button.setText(_translate("load_file", "女生"))
