# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_recipe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_recipe(object):
    def setupUi(self, new_recipe):
        new_recipe.setObjectName("new_recipe")
        new_recipe.resize(300, 400)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        new_recipe.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        new_recipe.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_recipe)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, 25, 50, 25)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choose_food_button = QtWidgets.QPushButton(new_recipe)
        self.choose_food_button.setObjectName("choose_food_button")
        self.verticalLayout_2.addWidget(self.choose_food_button)
        self.load_file_button = QtWidgets.QPushButton(new_recipe)
        self.load_file_button.setObjectName("load_file_button")
        self.verticalLayout_2.addWidget(self.load_file_button)
        self.first_page_button = QtWidgets.QPushButton(new_recipe)
        self.first_page_button.setObjectName("first_page_button")
        self.verticalLayout_2.addWidget(self.first_page_button)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(new_recipe)
        QtCore.QMetaObject.connectSlotsByName(new_recipe)

    def retranslateUi(self, new_recipe):
        _translate = QtCore.QCoreApplication.translate
        new_recipe.setWindowTitle(_translate("new_recipe", "新建食谱"))
        self.choose_food_button.setText(_translate("new_recipe", "选择食物"))
        self.load_file_button.setText(_translate("new_recipe", "从文件导入..."))
        self.first_page_button.setText(_translate("new_recipe", "返回"))
